### ISSUE TITLE
Serve decks via gh-pages

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#258] opened 2018-01-30 13:28 UTC
Hi,

It might be a good idea to host slides online. One way of doing this is to push html/static contents to gh-pages and let GitHub serve the static.

This can be automated using [Pages Deployment Provider @ Travis](https://docs.travis-ci.com/user/deployment/pages/).

Plz let me know if you'd like to have some help with this.

**Comment by IPvSean** [comment] 2018-01-30 13:31
We are in the process of doing this already.  You can actually see my setup of this hosted on https://ansible.com/net-lightbulb

**Comment by webknjaz** [comment] 2018-01-30 13:32
Would you please refer it in README?

**Comment by thedoubl3j** [comment] 2018-01-30 13:36
most definitely @webknjaz

**Comment by tima** [comment] 2018-01-30 21:45
This is a duplicate of #220 and as already noted this is under way with @jvanpelt leading that for us.

**Closed by tima** 2018-01-30 21:45 UTC
