### ISSUE TITLE
ec2 instances are provisioned synchronously

### ISSUE THREAD

**Issue by dswhitley** [ansible/lightbulb#234] opened 2017-11-21 21:30 UTC
When provisioning the instances required for a workshop, the provisioning of the ec2 instances is the most time consuming part of the playbook.

The `ec2` task in the [manage_ec2_instances](https://github.com/ansible/lightbulb/tree/master/tools/aws_lab_setup/roles/manage_ec2_instances) role is currently performed synchronously.  Could it be modified to behave [asynchronously](http://docs.ansible.com/ansible/latest/playbooks_async.html) to speed up workshop provisioning?

I imagine it will be very similar to http://toroid.org/ansible-parallel-dispatch

**Comment by IPvSean** [comment] 2017-11-21 21:34
@tima can you assign to me, I am working on this on https://github.com/network-automation/lightbulb/

**Comment by tima** [comment] 2017-11-21 22:29
This is a duplicate of #133.

**Closed by tima** 2017-11-21 22:29 UTC
Labels: duplicate, provisioner
