### ISSUE TITLE
Nginx workshop missing instruction to enable corresponding repo

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#282] opened 2018-02-16 16:20 UTC
Either
```
yum install epel-release
```

or
```yaml
- name: Add nginx repository
  yum_repository:
    name: nginx
    description: NginX YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
```

in playbook

**Comment by tima** [comment] 2018-02-16 16:36
This is a duplicate of #277.

In the other provisioners we've used EPEL as it gives us more options and flexibility to.

**Closed by tima** 2018-02-16 16:36 UTC
Labels: duplicate
